from django.contrib import admin
from .models import *


admin.site.register(UserInfo)
admin.site.register(Color0)
admin.site.register(Color1)
admin.site.register(Color2)
admin.site.register(Color3)
admin.site.register(Color4)
admin.site.register(Color5)
admin.site.register(Color6)
admin.site.register(Color7)
admin.site.register(Color8)
admin.site.register(Color9)
admin.site.register(Color10)
admin.site.register(Color11)
admin.site.register(Color12)
admin.site.register(Color13)
admin.site.register(Color14)
admin.site.register(Color15)
admin.site.register(Color16)
admin.site.register(Color17)
admin.site.register(Color18)
admin.site.register(Color19)
admin.site.register(Color20)
admin.site.register(Color21)
admin.site.register(Color22)
admin.site.register(Color23)
admin.site.register(Color24)
admin.site.register(Color25)
admin.site.register(Color26)
admin.site.register(Color27)
admin.site.register(Color28)
admin.site.register(Color29)
admin.site.register(Color30)
admin.site.register(Color31)
