from django.db import models


class UserInfo(models.Model):
    GENDER = [
        ('м', 'Мужской'),
        ('ж', 'Женский'),
        ('хз', 'Ваш пол'),
    ]
    ANSWER = [
        ('д', 'Да'),
        ('н', 'Нет'),
        ('хз', 'Есть ли у вас дальтонизм?')
    ]
    id = models.CharField('Id', max_length=1000, primary_key=True)
    age = models.IntegerField('Age')
    gender = models.CharField('Gender', max_length=30, choices=GENDER, default='хз')
    city = models.CharField('City', max_length=100)
    profession = models.CharField('Profession', max_length=100)
    daltonizm = models.CharField('Daltonizm', max_length=100, choices=ANSWER, default='хз')

    def __str__(self):
        return str(self.id)


class Color0(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color1(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color2(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color3(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color4(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color5(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color6(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color7(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color8(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color9(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color10(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color11(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color12(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color13(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color14(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color15(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color16(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color17(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color18(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color19(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color20(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color21(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color22(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color23(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color24(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color25(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color26(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color27(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color28(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color29(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color30(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')


class Color31(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    fKey = models.ForeignKey('UserInfo', on_delete=models.PROTECT, null='nothing')
    step0 = models.CharField('Step0', max_length=30, null='nothing')
    step1 = models.CharField('Step1', max_length=30, null='nothing')
    step2 = models.CharField('Step2', max_length=30, null='nothing')
    step3 = models.CharField('Step3', max_length=30, null='nothing')
    step4 = models.CharField('Step4', max_length=30, null='nothing')
    step5 = models.CharField('Step5', max_length=30, null='nothing')
    step6 = models.CharField('Step6', max_length=30, null='nothing')
    step7 = models.CharField('Step7', max_length=30, null='nothing')
    step8 = models.CharField('Step8', max_length=30, null='nothing')
    step9 = models.CharField('Step9', max_length=30, null='nothing')
    step15 = models.CharField('Step15', max_length=30, null='nothing')
    step14 = models.CharField('Step14', max_length=30, null='nothing')
    step13 = models.CharField('Step13', max_length=30, null='nothing')
    step11 = models.CharField('Step11', max_length=30, null='nothing')
    step10 = models.CharField('Step10', max_length=30, null='nothing')
    step12 = models.CharField('Step12', max_length=30, null='nothing')
    step16 = models.CharField('Step16', max_length=30, null='nothing')
    step17 = models.CharField('Step17', max_length=30, null='nothing')
    step18 = models.CharField('Step18', max_length=30, null='nothing')
    step19 = models.CharField('Step19', max_length=30, null='nothing')

# zecnfkfjn'njuj100
