# Generated by Django 4.1.7 on 2023-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3, verbose_name='Age')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('daltonizm', models.CharField(max_length=10, verbose_name='Daltonizm')),
            ],
        ),
    ]
