# Generated by Django 4.1.7 on 2023-03-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_info_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='UserInfo',
        ),
    ]
