# Generated by Django 4.1.7 on 2023-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('женщина', 'Женщина'), ('мужчина', 'Мужчина')], default='Ваш пол', max_length=30, verbose_name='Gender'),
        ),
    ]
