# Generated by Django 4.1.7 on 2023-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('ж', 'Женский'), ('м', 'Мужской'), ('хз', ' ')], max_length=30, verbose_name='Gender'),
        ),
    ]
