# Generated by Django 4.1.7 on 2023-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='daltonizm',
            field=models.CharField(choices=[('д', 'Да'), ('н', 'Нет'), ('хз', 'Есть ли у вас дальтонизм?')], default='хз', max_length=100, verbose_name='Daltonizm'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский'), ('хз', 'Ваш пол')], default='хз', max_length=30, verbose_name='Gender'),
        ),
    ]
