# Generated by Django 4.1.7 on 2023-03-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userinfo_daltonizm_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color12',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
            ],
        ),
        migrations.CreateModel(
            name='Color9',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color8',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color7',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color6',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color5',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color31',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color30',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color29',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color28',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color27',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color26',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color25',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color24',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color23',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color22',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color21',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color20',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color19',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color18',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color17',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color16',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color15',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color14',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color13',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color11',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color10',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Color0',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('step0', models.CharField(max_length=30, verbose_name='Step0')),
                ('step1', models.CharField(max_length=30, verbose_name='Step1')),
                ('step2', models.CharField(max_length=30, verbose_name='Step2')),
                ('step3', models.CharField(max_length=30, verbose_name='Step3')),
                ('step4', models.CharField(max_length=30, verbose_name='Step4')),
                ('step5', models.CharField(max_length=30, verbose_name='Step5')),
                ('step6', models.CharField(max_length=30, verbose_name='Step6')),
                ('step7', models.CharField(max_length=30, verbose_name='Step7')),
                ('step8', models.CharField(max_length=30, verbose_name='Step8')),
                ('step9', models.CharField(max_length=30, verbose_name='Step9')),
                ('step10', models.CharField(max_length=30, verbose_name='Step10')),
                ('step11', models.CharField(max_length=30, verbose_name='Step11')),
                ('step12', models.CharField(max_length=30, verbose_name='Step12')),
                ('step13', models.CharField(max_length=30, verbose_name='Step13')),
                ('step14', models.CharField(max_length=30, verbose_name='Step14')),
                ('step15', models.CharField(max_length=30, verbose_name='Step15')),
                ('step16', models.CharField(max_length=30, verbose_name='Step16')),
                ('step17', models.CharField(max_length=30, verbose_name='Step17')),
                ('step18', models.CharField(max_length=30, verbose_name='Step18')),
                ('step19', models.CharField(max_length=30, verbose_name='Step19')),
                ('fKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo')),
            ],
        ),
    ]
