# Generated by Django 4.1.7 on 2023-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_color1_step0_color1_step1_color1_step10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
