# Generated by Django 4.1.7 on 2023-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_color0_id_alter_color1_id_alter_color10_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id_P',
            field=models.CharField(default='0', max_length=1000, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
