# Generated by Django 4.1.7 on 2023-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userinfo_id_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.IntegerField(max_length=1000, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
