# Generated by Django 4.1.7 on 2023-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_userinfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id_copy',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
